stages:
    - build
    - test

cache:
    untracked: true
    paths:
        - node_modules/

Build:
    stage: build
    only:
        - develop
    before_script:
        - npm config set registry http://10.147.4.221:8081/repository/npm/
        - npm install
    script:
        - CI="" npm run build
    artifacts:
        paths:
            - build/

Test:
    stage: test
    only:
        - master
    script:
        - npm run test