stages:
    - test
    - build

cache:
    untracked: true
    paths:
        - node_modules/

Build:
    stage: build
    only:
        - develop
    before_script:
        - npm install
    script:
        - CI="" npm run build
    artifacts:
        paths:
            - build/

Test:
    stage: test
    only:
        - develop
    script:
        - npm run test